/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    ministries: Ministry;
    events: Event;
    'event-registrations': EventRegistration;
    sermons: Sermon;
    'media-gallery-items': MediaGalleryItem;
    resources: Resource;
    testimonials: Testimonial;
    'bookstore-items': BookstoreItem;
    donations: Donation;
    'prayer-requests': PrayerRequest;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    'media-gallery-items': MediaGalleryItemsSelect<false> | MediaGalleryItemsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'bookstore-items': BookstoreItemsSelect<false> | BookstoreItemsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'prayer-requests': PrayerRequestsSelect<false> | PrayerRequestsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    giving: Giving;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    giving: GivingSelect<false> | GivingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Controls what this person can see and edit in the admin panel.
   */
  role: 'super-admin' | 'admin' | 'content-editor' | 'ministry-leader' | 'volunteer';
  /**
   * For Ministry Leaders: which ministry/ministries this person manages.
   */
  ministries?: (number | Ministry)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  name: string;
  /**
   * Auto-generated from the name if left blank. Used in the page URL.
   */
  slug: string;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. If left empty, an icon is shown instead.
   */
  image?: (number | null) | Media;
  /**
   * Shown when no photo is uploaded. Leave unset to auto-pick one based on the ministry name.
   */
  icon?:
    | (
        | 'cross'
        | 'book'
        | 'flame'
        | 'heart'
        | 'users'
        | 'prayer'
        | 'globe'
        | 'church'
        | 'sparkles'
        | 'water'
        | 'sun'
        | 'music'
        | 'home'
        | 'compass'
        | 'crown'
        | 'scroll'
        | 'lightbulb'
        | 'star'
        | 'dove'
        | 'shield'
        | 'eye'
        | 'target'
        | 'pin'
        | 'handshake'
      )
    | null;
  leaderName?: string | null;
  meetingTimes?:
    | {
        label: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO — required for accessibility.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug: string;
  /**
   * Short line shown under the page title in the banner at the top of the page.
   */
  subtitle?: string | null;
  /**
   * Optional — nests this page under another (e.g. About subpages).
   */
  parent?: (number | null) | Page;
  layout?:
    | (
        | {
            headline: string;
            subheadline?: string | null;
            backgroundImage?: (number | null) | Media;
            ctaButtons?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Leave a blank line between paragraphs.
             */
            body?: string | null;
            /**
             * Optional short checklist shown under the text.
             */
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional photo. If left empty, a branded panel with the church logo is shown instead.
             */
            image?: (number | null) | Media;
            imagePosition?: ('right' | 'left') | null;
            background?: ('light' | 'tinted') | null;
            buttonLabel?: string | null;
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitFeature';
          }
        | {
            heading?: string | null;
            eyebrow?: string | null;
            /**
             * Optional short paragraph shown under the heading.
             */
            intro?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  title: string;
                  body: string;
                  /**
                   * Optional icon shown at the top of the card.
                   */
                  icon?:
                    | (
                        | 'cross'
                        | 'book'
                        | 'flame'
                        | 'heart'
                        | 'users'
                        | 'prayer'
                        | 'globe'
                        | 'church'
                        | 'sparkles'
                        | 'water'
                        | 'sun'
                        | 'music'
                        | 'home'
                        | 'compass'
                        | 'crown'
                        | 'scroll'
                        | 'lightbulb'
                        | 'star'
                        | 'dove'
                        | 'shield'
                        | 'eye'
                        | 'target'
                        | 'pin'
                        | 'handshake'
                      )
                    | null;
                  /**
                   * Optional small line at the bottom, e.g. a scripture reference.
                   */
                  footnote?: string | null;
                  /**
                   * Optional link — makes the whole card clickable. Use /about/history for pages on this site, or a full https:// address for other websites.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  /**
                   * A year or a phase name, e.g. "1999" or "The Beginning".
                   */
                  label: string;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGrid';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            eyebrow?: string | null;
            /**
             * Show the first person as a large highlighted card (e.g. the Lead Pastor).
             */
            featureFirst?: boolean | null;
            members?:
              | {
                  name: string;
                  title?: string | null;
                  /**
                   * A portrait photo. If empty, a coloured card with their initials is shown.
                   */
                  photo?: (number | null) | Media;
                  bio?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamGrid';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            buttonUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqAccordion';
          }
        | {
            heading?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsBlock';
          }
        | {
            heading?: string | null;
            /**
             * A YouTube/video URL, map link, or other embeddable URL.
             */
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  photo?: (number | null) | Media;
  quote: string;
  relatedMinistry?: (number | null) | Ministry;
  /**
   * Contact email for follow-up only — never shown publicly.
   */
  submitterEmail?: string | null;
  /**
   * Testimonies submitted by the public start as Pending Review and are hidden from the site until switched to Approved here.
   */
  status?: ('pending-review' | 'approved') | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug: string;
  type: 'programme' | 'conference' | 'mission' | 'regular';
  startDate: string;
  endDate?: string | null;
  location?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  relatedMinistry?: (number | null) | Ministry;
  externalRegistrationLink?: string | null;
  /**
   * Let people RSVP for this event directly on the site.
   */
  registrationEnabled?: boolean | null;
  /**
   * Maximum total attendees. Leave blank for unlimited.
   */
  capacity?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Total number of people this registration covers, including the registrant.
   */
  guests: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug: string;
  speaker?: string | null;
  date: string;
  series?: string | null;
  scriptureReference?: string | null;
  audioUrl?: string | null;
  videoUrl?: string | null;
  thumbnail?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gallery-items".
 */
export interface MediaGalleryItem {
  id: number;
  title: string;
  category: 'gallery' | 'cog-tv' | 'cog-grand-radio';
  images?: (number | Media)[] | null;
  /**
   * YouTube or other video URL, for COG TV items.
   */
  videoEmbedUrl?: string | null;
  relatedMinistry?: (number | null) | Ministry;
  relatedEvent?: (number | null) | Event;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug: string;
  type: 'start-here' | 'devotional' | 'reading-plan' | 'topical-guide';
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  file?: (number | null) | Media;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookstore-items".
 */
export interface BookstoreItem {
  id: number;
  title: string;
  author?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * e.g. "£9.99"
   */
  priceDisplay?: string | null;
  externalPurchaseLink: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Records of online gifts made through Stripe. Created automatically when someone starts giving on /give/donate, and marked Completed by the Stripe webhook once payment succeeds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  donorName: string;
  donorEmail: string;
  /**
   * In pence (e.g. 2500 = £25.00), matching Stripe's own convention.
   */
  amount: number;
  branch: string;
  fund: string;
  frequency: 'one-time' | 'monthly';
  /**
   * HMRC requires a home address + postcode for a valid Gift Aid declaration.
   */
  giftAid?: {
    declared?: boolean | null;
    fullName?: string | null;
    address?: string | null;
    postcode?: string | null;
  };
  status?: ('pending' | 'completed' | 'failed') | null;
  /**
   * When Stripe confirmed payment — distinct from createdAt (when the donor started checkout).
   */
  paidAt?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  /**
   * Set on recurring renewal charges (from invoice.paid) — prevents double-recording the same charge.
   */
  stripeInvoiceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests".
 */
export interface PrayerRequest {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  request: string;
  isConfidential?: boolean | null;
  status?: ('new' | 'in-progress' | 'prayed-for') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formType: 'contact' | 'appointment' | 'membership' | 'reference-letter';
  name: string;
  email: string;
  phone?: string | null;
  preferredDate?: string | null;
  /**
   * Which ministry they want to join.
   */
  interestedMinistry?: (number | null) | Ministry;
  letterType?: ('character' | 'membership-confirmation' | 'financial' | 'other') | null;
  /**
   * What the reference letter is for.
   */
  purpose?: string | null;
  requiredByDate?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'media-gallery-items';
        value: number | MediaGalleryItem;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'bookstore-items';
        value: number | BookstoreItem;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'prayer-requests';
        value: number | PrayerRequest;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  ministries?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  parent?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              backgroundImage?: T;
              ctaButtons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        splitFeature?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              imagePosition?: T;
              background?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              heading?: T;
              eyebrow?: T;
              intro?: T;
              columns?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    icon?: T;
                    footnote?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageGrid?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              heading?: T;
              eyebrow?: T;
              featureFirst?: T;
              members?:
                | T
                | {
                    name?: T;
                    title?: T;
                    photo?: T;
                    bio?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        faqAccordion?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              heading?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              heading?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  icon?: T;
  leaderName?: T;
  meetingTimes?:
    | T
    | {
        label?: T;
        time?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  description?: T;
  featuredImage?: T;
  relatedMinistry?: T;
  externalRegistrationLink?: T;
  registrationEnabled?: T;
  capacity?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  email?: T;
  phone?: T;
  guests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  speaker?: T;
  date?: T;
  series?: T;
  scriptureReference?: T;
  audioUrl?: T;
  videoUrl?: T;
  thumbnail?: T;
  description?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gallery-items_select".
 */
export interface MediaGalleryItemsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  images?: T;
  videoEmbedUrl?: T;
  relatedMinistry?: T;
  relatedEvent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  body?: T;
  file?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  quote?: T;
  relatedMinistry?: T;
  submitterEmail?: T;
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookstore-items_select".
 */
export interface BookstoreItemsSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  coverImage?: T;
  priceDisplay?: T;
  externalPurchaseLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  donorName?: T;
  donorEmail?: T;
  amount?: T;
  branch?: T;
  fund?: T;
  frequency?: T;
  giftAid?:
    | T
    | {
        declared?: T;
        fullName?: T;
        address?: T;
        postcode?: T;
      };
  status?: T;
  paidAt?: T;
  stripeCheckoutSessionId?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripeInvoiceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests_select".
 */
export interface PrayerRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  request?: T;
  isConfidential?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  email?: T;
  phone?: T;
  preferredDate?: T;
  interestedMinistry?: T;
  letterType?: T;
  purpose?: T;
  requiredByDate?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName: string;
  serviceTimes?:
    | {
        label: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  address?: {
    line1?: string | null;
    city?: string | null;
    postcode?: string | null;
  };
  contactEmail?: string | null;
  contactPhone?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    /**
     * COG Grand Radio (external site)
     */
    radioUrl?: string | null;
    /**
     * Powers the live stream embed on COG TV. This is the channel's ID (starts with UC…), not the @handle — find it on the channel's About page under 'Share channel'.
     */
    youtubeChannelId?: string | null;
  };
  nav?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  homepageHero?: {
    headline?: string | null;
    tagline?: string | null;
    /**
     * Short spoken-word line, e.g. "A Place where God lives and Miracles happen Naturally."
     */
    declarationLine?: string | null;
    backgroundImage?: (number | null) | Media;
    /**
     * A direct .mp4 URL for a looping hero video. Takes priority over the background image when set.
     */
    backgroundVideoUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "giving".
 */
export interface Giving {
  id: number;
  /**
   * Shown on the Give page as a "Bank Transfer" option. Leave Account Name blank to hide this option entirely.
   */
  bankTransfer?: {
    /**
     * e.g. City of God Christian Centre
     */
    accountName?: string | null;
    /**
     * e.g. 12-34-56
     */
    sortCode?: string | null;
    accountNumber?: string | null;
    /**
     * e.g. "Please use your name as the payment reference"
     */
    referenceNote?: string | null;
  };
  /**
   * Which branch a donor is giving to, shown on the online giving page. The first one is used as the default selection.
   */
  branches?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Funds a donor can choose from on the online giving page. The first one is used as the default selection.
   */
  funds?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Fallback link shown only if Stripe isn't configured (no STRIPE_SECRET_KEY) — e.g. a Tithe.ly or GoCardless page. Once Stripe is set up, the "Give Online" button uses the native /give/donate flow instead and this is ignored. Leave URL blank to show "coming soon" in the meantime.
   */
  onlineGiving?: {
    url?: string | null;
    label?: string | null;
  };
  /**
   * Optional. Shown in the Gift Aid section if set.
   */
  charityNumber?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  serviceTimes?:
    | T
    | {
        label?: T;
        time?: T;
        id?: T;
      };
  address?:
    | T
    | {
        line1?: T;
        city?: T;
        postcode?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        radioUrl?: T;
        youtubeChannelId?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerText?: T;
  homepageHero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        declarationLine?: T;
        backgroundImage?: T;
        backgroundVideoUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "giving_select".
 */
export interface GivingSelect<T extends boolean = true> {
  bankTransfer?:
    | T
    | {
        accountName?: T;
        sortCode?: T;
        accountNumber?: T;
        referenceNote?: T;
      };
  branches?:
    | T
    | {
        name?: T;
        id?: T;
      };
  funds?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  onlineGiving?:
    | T
    | {
        url?: T;
        label?: T;
      };
  charityNumber?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}